version: '3.8'

services:
  server:
    build:
      context: .
      target: development
    ports:
      - "50051:50051"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: bun run dev